/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as StaffingRouteImport } from './routes/staffing'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as SmsPrivacyRouteImport } from './routes/sms-privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReferAFriendRouteImport } from './routes/refer-a-friend'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProviderInquiryRouteImport } from './routes/provider-inquiry'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as CtInspect7b2e1dRouteImport } from './routes/ct-inspect-7b2e1d'
import { Route as CredentialingRouteImport } from './routes/credentialing'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as ClientInquiryRouteImport } from './routes/client-inquiry'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingRoute = StaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsPrivacyRoute = SmsPrivacyRouteImport.update({
  id: '/sms-privacy',
  path: '/sms-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferAFriendRoute = ReferAFriendRouteImport.update({
  id: '/refer-a-friend',
  path: '/refer-a-friend',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderInquiryRoute = ProviderInquiryRouteImport.update({
  id: '/provider-inquiry',
  path: '/provider-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const CtInspect7b2e1dRoute = CtInspect7b2e1dRouteImport.update({
  id: '/ct-inspect-7b2e1d',
  path: '/ct-inspect-7b2e1d',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialingRoute = CredentialingRouteImport.update({
  id: '/credentialing',
  path: '/credentialing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInquiryRoute = ClientInquiryRouteImport.update({
  id: '/client-inquiry',
  path: '/client-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/client-inquiry': typeof ClientInquiryRoute
  '/consulting': typeof ConsultingRoute
  '/credentialing': typeof CredentialingRoute
  '/ct-inspect-7b2e1d': typeof CtInspect7b2e1dRoute
  '/inquiry': typeof InquiryRoute
  '/investors': typeof InvestorsRoute
  '/leadership': typeof LeadershipRoute
  '/provider-inquiry': typeof ProviderInquiryRoute
  '/providers': typeof ProvidersRoute
  '/refer-a-friend': typeof ReferAFriendRoute
  '/services': typeof ServicesRoute
  '/sms-privacy': typeof SmsPrivacyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/staffing': typeof StaffingRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/client-inquiry': typeof ClientInquiryRoute
  '/consulting': typeof ConsultingRoute
  '/credentialing': typeof CredentialingRoute
  '/ct-inspect-7b2e1d': typeof CtInspect7b2e1dRoute
  '/inquiry': typeof InquiryRoute
  '/investors': typeof InvestorsRoute
  '/leadership': typeof LeadershipRoute
  '/provider-inquiry': typeof ProviderInquiryRoute
  '/providers': typeof ProvidersRoute
  '/refer-a-friend': typeof ReferAFriendRoute
  '/services': typeof ServicesRoute
  '/sms-privacy': typeof SmsPrivacyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/staffing': typeof StaffingRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/client-inquiry': typeof ClientInquiryRoute
  '/consulting': typeof ConsultingRoute
  '/credentialing': typeof CredentialingRoute
  '/ct-inspect-7b2e1d': typeof CtInspect7b2e1dRoute
  '/inquiry': typeof InquiryRoute
  '/investors': typeof InvestorsRoute
  '/leadership': typeof LeadershipRoute
  '/provider-inquiry': typeof ProviderInquiryRoute
  '/providers': typeof ProvidersRoute
  '/refer-a-friend': typeof ReferAFriendRoute
  '/services': typeof ServicesRoute
  '/sms-privacy': typeof SmsPrivacyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/staffing': typeof StaffingRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/client-inquiry'
    | '/consulting'
    | '/credentialing'
    | '/ct-inspect-7b2e1d'
    | '/inquiry'
    | '/investors'
    | '/leadership'
    | '/provider-inquiry'
    | '/providers'
    | '/refer-a-friend'
    | '/services'
    | '/sms-privacy'
    | '/sms-terms'
    | '/staffing'
    | '/telemedicine'
    | '/terms'
    | '/thank-you'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/client-inquiry'
    | '/consulting'
    | '/credentialing'
    | '/ct-inspect-7b2e1d'
    | '/inquiry'
    | '/investors'
    | '/leadership'
    | '/provider-inquiry'
    | '/providers'
    | '/refer-a-friend'
    | '/services'
    | '/sms-privacy'
    | '/sms-terms'
    | '/staffing'
    | '/telemedicine'
    | '/terms'
    | '/thank-you'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/client-inquiry'
    | '/consulting'
    | '/credentialing'
    | '/ct-inspect-7b2e1d'
    | '/inquiry'
    | '/investors'
    | '/leadership'
    | '/provider-inquiry'
    | '/providers'
    | '/refer-a-friend'
    | '/services'
    | '/sms-privacy'
    | '/sms-terms'
    | '/staffing'
    | '/telemedicine'
    | '/terms'
    | '/thank-you'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ClientInquiryRoute: typeof ClientInquiryRoute
  ConsultingRoute: typeof ConsultingRoute
  CredentialingRoute: typeof CredentialingRoute
  CtInspect7b2e1dRoute: typeof CtInspect7b2e1dRoute
  InquiryRoute: typeof InquiryRoute
  InvestorsRoute: typeof InvestorsRoute
  LeadershipRoute: typeof LeadershipRoute
  ProviderInquiryRoute: typeof ProviderInquiryRoute
  ProvidersRoute: typeof ProvidersRoute
  ReferAFriendRoute: typeof ReferAFriendRoute
  ServicesRoute: typeof ServicesRoute
  SmsPrivacyRoute: typeof SmsPrivacyRoute
  SmsTermsRoute: typeof SmsTermsRoute
  StaffingRoute: typeof StaffingRoute
  TelemedicineRoute: typeof TelemedicineRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing': {
      id: '/staffing'
      path: '/staffing'
      fullPath: '/staffing'
      preLoaderRoute: typeof StaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-privacy': {
      id: '/sms-privacy'
      path: '/sms-privacy'
      fullPath: '/sms-privacy'
      preLoaderRoute: typeof SmsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-a-friend': {
      id: '/refer-a-friend'
      path: '/refer-a-friend'
      fullPath: '/refer-a-friend'
      preLoaderRoute: typeof ReferAFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-inquiry': {
      id: '/provider-inquiry'
      path: '/provider-inquiry'
      fullPath: '/provider-inquiry'
      preLoaderRoute: typeof ProviderInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-inspect-7b2e1d': {
      id: '/ct-inspect-7b2e1d'
      path: '/ct-inspect-7b2e1d'
      fullPath: '/ct-inspect-7b2e1d'
      preLoaderRoute: typeof CtInspect7b2e1dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentialing': {
      id: '/credentialing'
      path: '/credentialing'
      fullPath: '/credentialing'
      preLoaderRoute: typeof CredentialingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-inquiry': {
      id: '/client-inquiry'
      path: '/client-inquiry'
      fullPath: '/client-inquiry'
      preLoaderRoute: typeof ClientInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ClientInquiryRoute: ClientInquiryRoute,
  ConsultingRoute: ConsultingRoute,
  CredentialingRoute: CredentialingRoute,
  CtInspect7b2e1dRoute: CtInspect7b2e1dRoute,
  InquiryRoute: InquiryRoute,
  InvestorsRoute: InvestorsRoute,
  LeadershipRoute: LeadershipRoute,
  ProviderInquiryRoute: ProviderInquiryRoute,
  ProvidersRoute: ProvidersRoute,
  ReferAFriendRoute: ReferAFriendRoute,
  ServicesRoute: ServicesRoute,
  SmsPrivacyRoute: SmsPrivacyRoute,
  SmsTermsRoute: SmsTermsRoute,
  StaffingRoute: StaffingRoute,
  TelemedicineRoute: TelemedicineRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
